# - - - - - - - - - Do not change these settings - - - - - - - - -"
theme: 
url: https://dartsatlas.github.io/player-website-template
sass:
  sass_dir: _sass/
# - - - - - - - - - You can edit below this line - - - - - - - - -"
# Player Details
title: "\"Lazer Cat\" Matt Langan"
player_bio: Lazer Cat is a professional amateur darts player who throws and live streams from his laundry room in Austin, Texas.
hometown: Austin, Texas
# Organization Information
league: Quarantine League
rank: 7
next_event: qTour 5
results:
  -
    event: qTour 2
    result: Semi Final
news: Lazer Cat will be re-joining the Quarantine League for the Spring 2021 season!
media_inquiries: media@dartsatlas.com
business_inquiries: zapzapmeow@dartsatlas.com

# Images
header_image: assets/img/banner.jpg
player_headshot: assets/img/headshot.png

# Social Media Links
twitter: https://twitter.com/mattlangan
facebook: https://facebook.com/mattlangan
youtube: https://youtube.com/cityleaguedarts
instagram: https://instagram.com/cityleaguedarts

# Sponsors
sponsors:
  -
    name: Sponsor 1
    image: sponsor_image.jpg
    url: https://sponsorwebsite.com
  -
    name: Sponsor 2
    image: sponsor_image_2.jpg
    url: https://sponsorwebsite2.com
