# - - - - - - - - - Do not change these settings - - - - - - - - -"
theme: 
url: https://dartsatlas.github.io/player-website-template
sass:
  sass_dir: _sass/
# - - - - - - - - - You can edit below this line - - - - - - - - -"
# Player Details
title: "\"Lazer Cat\" Matt Langan"
player_bio: Lazer Cat is a professional amateur darts player who throws and live streams from his laundry room in Austin, Texas.
hometown: Austin, Texas
# Organization Information
league: Quarantine League
rank: 7
next_event: qTour 5 (March 11)
recent_results:
  -
    event: qTour 2
    result: Semi Final
news: Lazer Cat will be re-joining the Quarantine League for the Spring 2021 season!
media_inquiries: media@dartsatlas.com
business_inquiries: zapzapmeow@dartsatlas.com

# Branding
theme_color: '#1F5C23'
banner_image: banner.jpg
player_headshot: headshot.png

# Social Media Links
# Make sure you include the "https://" prefix
twitter: https://twitter.com/mattlangan
facebook: https://facebook.com/mattlangan
youtube: https://youtube.com/cityleaguedarts
instagram: https://instagram.com/cityleaguedarts

# Sponsors
# Place the image in /assets/img/sponsors/
sponsors:
  -
    name: Darts Atlas
    image: darts-atlas.png
    url: https://www.dartsatlas.com
  -
    name: City League Darts
    image: city-league.png
    url: https://www.cityleaguedarts.com
  -
    name: Weekly Dartscast
    image: weekly-dartscast.jpg
    url: https://www.weeklydartscast.com
